# General
permalink   : /:categories/:title/
highlighter : rouge

title: Harbor
description: "All-in-one 401(k) plan"
keywords: affordable, modern, 401(k), retirement, full-service, automated, pre-tax, auto-enrollment, HR-tech, Fintech, Chicago, Illinois, mobile, compliance, fiduciary
email: tripathi@vesthq.com
url: https://harborhq.com
repository: https://github.com/VestHQ/HarborHQ
google_analytics: UA-122850848-1

sass:
  sass_dir: _sass
  style: compressed

exclude: [".idea/"]

# Build settings
markdown: kramdown
theme: minima


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-autoprefixer

autoprefixer:
  browsers:
  - last 6 versions